### ISSUE TITLE
rating reverse (left to right)

### ISSUE THREAD

**Issue by jamal-pb95** [techdiary-dev/Techdiary#13]
**আপনি যে সমস্যা(Bug) পেয়েছেন সেটি সংক্ষেপে ব্যক্ত করুন**
টেকডাইরি এর রেটিং বাম থেকে ডানে hate - love আছে। আমি মনে করছি love - hate হউয়া উচিত।

**আপনি যেমনটি আশা করেছিলেন (Expected behavior)**

**কিছু স্ক্রিনশট**
![image](https://user-images.githubusercontent.com/20262255/86553873-c2471400-bf6d-11ea-975e-06067474464c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version : Latest

**Comment by kingRayhan** [comment]
আমরা একটি thirdparty সার্ভিস ব্যবহার করছি। সেখানে এটি রিভার্স করার অপশন নাই। 
আপনার ফিডব্যাক এর জন্যে অসংখ্য ধন্যবাদ।
