### ISSUE TITLE
💄 ছবির নিচে যেনো ক্রেডিট দেয়া যায়।

### ISSUE THREAD

**Issue by asifadib** [techdiary-dev/techdiary#14]
অনেক সময় ব্লগ লিখার সময় বিভিন্ন ছবি ব্যবহার করতে হয় যেগুলোতে ছবির প্রস্তুতকারকে ক্রেডিট দিতে হয়। এই বিষয়টা দেখবেন এইটা টেক ডায়রির এস সি ও এর জন্যও ভালো নয়। আশাকরি দ্রুত ব্যবস্থা গ্রহন করা হবে।
ধন্যবাদ

**Comment by kingRayhan** [comment]
ফিচার রিকুয়েস্ট এর জন্যে ধন্যবাদ। খুব তাড়াতাড়িই এটি যুক্ত করা হয়।

**Comment by shoaibsharif** [comment]
We have implemented this feature in our new techdiary version. Our old version will soon be deprecated. For now, please visit [our new website](https://v3.techdiary.dev) and feel free to create any issue based on that. Thank you and we appreciate your concerns.

**Comment by asifadib** [comment]
ধন্যবাদ ভাই এই ফিচারটি SEO এর জন্য বেশ গুরুত্বপূর্ণ ছিলো।  🔥🔥
