### ISSUE TITLE
left side bar not show properly

### ISSUE THREAD

**Issue by DihanAbir** [techdiary-dev/Techdiary#15]
**আপনি যে সমস্যা(Bug) পেয়েছেন সেটি সংক্ষেপে ব্যক্ত করুন**
// TODO: .. bug এর description এখানে লিখব

**আপনি যেমনটি আশা করেছিলেন (Expected behavior)**

**কিছু স্ক্রিনশট**
![image](https://user-images.githubusercontent.com/48027481/89259948-2cc2a100-d64d-11ea-9771-c634e64fd041.png)
![talkdiarary ](https://user-images.githubusercontent.com/48027481/89260021-449a2500-d64d-11ea-932f-b1260e9c009c.PNG)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by kingRayhan** [comment]
Thanks for this issue. 

Can you check again now?

**Comment by kingRayhan** [comment]
issue fixed 😄 

![image](https://user-images.githubusercontent.com/7611746/89313086-df205580-d699-11ea-8737-f182a0cf7d64.png)

**Comment by DihanAbir** [comment]
yeah , fixed now :)
