### ISSUE TITLE
🐞 আর্টিকেল লেখার সময় স্পেস ঠিক ভাবে কাজ করে না !!

### ISSUE THREAD

**Issue by asifadib** [techdiary-dev/techdiary#16]
**আপনি যে সমস্যা(Bug) পেয়েছেন সেটি সংক্ষেপে ব্যক্ত করুন**

আর্টিকেল লেখার সময় স্পেস ঠিক ভাবে কাজ করে না !!

**আপনি যেমনটি আশা করেছিলেন (Expected behavior)**

আর্টিকেল লেখার সময় স্পেস ঠিক ভাবে কাজ না করলে আর্টিকেল ঠিকভাবে উপস্থাপন করতে অনেক অসুবিধা হয়।

**কিছু স্ক্রিনশট**

এখানে দুইটা স্ক্রিনশট যুক্ত করেছি বুঝার সুবিধার জন্য।

1. https://prnt.sc/tto8y4

2. https://prnt.sc/ttoa5r

**Comment by kingRayhan** [comment]
Thanks for this bug report
