### ISSUE TITLE
💄 লিংকে কালো কালার না রেখে অন্য কোন একটা কালার ব্যবহার করলে ভালো হয়। 

### ISSUE THREAD

**Issue by asifadib** [techdiary-dev/techdiary#17]
আর্টিকেলের মাঝে  লিংকে কালো কালার না রেখে অন্য একটা কালার ব্যবহার করলে অনেক সুবিধা হবে আর্টিকেল পড়ার সময়।

**Comment by shoaibsharif** [comment]
Please create any issue based on our new website and feel free to create a new issue. I will close this issue since it was for old website.
