### ISSUE TITLE
🐞 নতুন ব্যবহারকারীদের ক্ষেত্রে গিটহাব দিয়ে লগইন করতে সমস্যা হচ্ছে।

### ISSUE THREAD

**Issue by bulbulahmed9** [techdiary-dev/techdiary#29]
log in করার জন্য যখন 'যুক্ত হন' এ click করলাম তখন আমার কাছে github এর authorization permission চাইলো।  আমি দিলাম।  কিন্তু redirect  করে আবার আমাকে পূর্বের page এ নিয়ে আসলো।  আবার authorization permission দিলাম।  কিন্তু আগের মতোই ঘটনা ঘটলো।  লগ ইন হচ্ছিলো না।  কিন্তু page  refresh  দেয়ার পর login হয়েছে।

**Comment by shoaibsharif** [comment]
Ctrl + Shift + R দেয়ার পরেও লগইন এ  সমস্যা করে? জানাবেন। এবং প্রবলেম জানানোর জন্যে অসংখ্য ধন্যবাদ।

**Comment by kingRayhan** [comment]
@shoaibsharif ভাই আমি সেটা বুঝেছি সেটা হচ্ছে নতুন ব্যবহারকারীদের সমস্যা হচ্ছে, পুরাতন ব্যবহারকারীদের লগইন করতে সমস্যা হচ্ছে না।
