### ISSUE TITLE
🔥 পিন পোস্ট সেকশনটা বাদ দিতে হবে 

### ISSUE THREAD

**Issue by asifadib** [techdiary-dev/Techdiary#36]
![image](https://user-images.githubusercontent.com/45002778/89706257-b5ab4680-d985-11ea-9760-3ec42121c9e3.png)

পিন পোস্ট সেকশনটা বাদ দিয়ে দিলে লেটেস্ট আর্টিকেল গুলো উপরে থাকবে এইটা ব্যবহারকারীর জন্য অনেক ইউসফুল হয়। পিন পোস্ট এর পরিবর্তে একদম উপরে যে স্লাইডার সেকশন রয়েছে তার মাঝে, সপ্তাহিক বা মাসিক বা সবসময়ের সেরা আর্টিকেল গুলো ফিচার করলে অনেক ভালো হবে।  এইটা একটু ভেবে দেখবেন। 
ধন্যবাদ

**Comment by kingRayhan** [comment]
ভাইয়া আপনার সাজেশন এর জন্যে অনেক ধন্যবাদ। এই ফিচারটা আমরা মূলত নিয়ে এসেছিলাম বিষয় কোন নোটিশ দেয়ার জন্যে বা ভালো আর্টিক্যাল গুলিকে কিছুদিন উপরে রাখার জন্যে। আমরা এখন থেকে নোটিশ ছাড়া অন্যকোন কাজে এ এই পিন ফিচার টি ব্যবহার করব না।

**Comment by shoaibsharif** [comment]
In our new website, we have removed this section. Please check our new website and let's us know how you liked it. I will close this issue since it was for our old website.
