### ISSUE TITLE
🙏  গুগল এবং ফেসবুক দিয়ে লগিন করার সুবিদা চাই।

### ISSUE THREAD

**Issue by kingRayhan** [techdiary-dev/Techdiary#37]
বর্তমানে আমরা টেমডায়েরিতে কেবলমাত্র গিটহাব দিয়ে লগইন করা যাচ্ছে। গিটহাব এর পাশাপাশি গুগল এবং ফেসবুক দিয়ে লগইন করার সুবিদাও আনা জরুরি আমার মনে হয়।

**Comment by shoaibsharif** [comment]
Is it necessary?

**Comment by kingRayhan** [comment]
জ্বী ভাই, আমার মনে হয় আরও কিছু লগইন প্রোভাইডার যুক্ত করা দরকার।

**Comment by kingRayhan** [comment]
Added
