### ISSUE TITLE
কিছুটা সমস্যা প্রোফাইল ড্রপ ডাউন এর মধ্যে স্লাইডার এর বাটন টা উপড়ে রয়ে গেছে যা দৃষ্টি কটু 

### ISSUE THREAD

**Issue by Taraldinn** [techdiary-dev/Techdiary#41]
**কিছু স্ক্রিনশট**

![image](https://user-images.githubusercontent.com/59772487/101986000-800cc600-3cb5-11eb-894d-6d300124cbf0.png)

**Comment by shoaibsharif** [comment]
I will close this issue since we have implemented whole new design
