### ISSUE TITLE
🐞  সার্চবার কাজ করছে না 

### ISSUE THREAD

**Issue by naeemdev360** [techdiary-dev/Techdiary#44]
**আপনি যে সমস্যা(Bug) পেয়েছেন সেটি সংক্ষেপে ব্যক্ত করুন**
// TODO: .. bug এর description এখানে লিখব
সার্চবার দ্বারা অনুসন্ধান করতে পারছি না। 
**আপনি যেমনটি আশা করেছিলেন (Expected behavior)**

**কিছু স্ক্রিনশট**
![Screenshot_1](https://user-images.githubusercontent.com/41102994/111912455-d5fec000-8a93-11eb-9bbe-480746e5d7ec.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 89.0.4389.90 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Comment by shoaibsharif** [comment]
Thank you  for your concern and we appreciate it. Currently we are working with new website design and bringing more stability. You can visit [our new Techdiary website](https://v3.techdiary.dev). If you find any more issues, please don't hasitate to bring that on to us.
