### ISSUE TITLE
🐞  User Profile articles on hover issue with dark mode

### ISSUE THREAD

**Issue by shoaibsharif** [techdiary-dev/Techdiary#45]
**আপনি যে সমস্যা(Bug) পেয়েছেন সেটি সংক্ষেপে ব্যক্ত করুন**
Issue with dark more on profile page when user hover on diaries.

**আপনি যেমনটি আশা করেছিলেন (Expected behavior)**
i would like to see the fix when I hover on diaries.

**কিছু স্ক্রিনশট**
![CleanShot 2021-03-22 at 11 39 15](https://user-images.githubusercontent.com/29075110/112042020-47765700-8b04-11eb-8aa2-e6fc77e48f6d.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by kingRayhan** [comment]
Solved
