### ISSUE TITLE
💄 আগুন্তুক বাটনটা কাজ করছে নাহ ! 

### ISSUE THREAD

**Issue by Taraldinn** [techdiary-dev/Techdiary#48]
![image](https://user-images.githubusercontent.com/59772487/112372092-8b867900-8d09-11eb-9050-3d0d68c80005.png)
এখানে একটু ফিক্স করতে হবে

**Comment by shoaibsharif** [comment]
This was on purpose. What do you think? @kingRayhan

**Comment by kingRayhan** [comment]
আমার মনে হয় এটাকে ক্লিকেবল করলেই ভালো হয়, তাহলে যে কোন পেইজ থেকে লগইন করা যাবে।

**Comment by shoaibsharif** [comment]
Fixed on new commit. Closing
