### ISSUE TITLE
🐞  need some change on font ... 

### ISSUE THREAD

**Issue by Taraldinn** [techdiary-dev/Techdiary#52]
use on heading = hind shiliguri
use on paragraph = kohinoor /boshonto/riju

**Comment by ahsanhabibsunny365** [comment]
Dashboard ডিজাইন পরিবর্তন চাই।উপরে ব্যানার থাকবে Profile pic এর উপরে অনেকটা Facebook Cover এর মতো । github ছাড়াও Google facebook Apple twitter Email গুলো Login এর ব্যবস্তা করলে ভালো হয়। CUSTOM user name creat করা System. Font কূহিনুর ব্যবহার করলে ভালো হয়। schedule system post করা।

**Comment by Taraldinn** [comment]
> Dashboard ডিজাইন পরিবর্তন চাই।উপরে ব্যানার থাকবে Profile pic এর উপরে অনেকটা Facebook Cover এর মতো । github ছাড়াও Google facebook Apple twitter Email গুলো Login এর ব্যবস্তা করলে ভালো হয়। CUSTOM user name creat করা System. Font কূহিনুর ব্যবহার করলে ভালো হয়। schedule system post করা।

thanks to @ahsanhabibsunny365 আমারা চাইছি নাহ প্রথমত নন ডেভলপার কেউ এই সাইট এ জয়েন করুক তাই আমরা গিট হাব ছাড়া আর কোন লগ ইন অপ্সন রাখি নি । আর বাকি ফিচার গুলা ভেবে দেখব !

**Comment by shoaibsharif** [comment]
Some issue 

![image](https://user-images.githubusercontent.com/29075110/116163772-41e4d180-a6ad-11eb-9c5b-fd4e2f998bba.png)
