### ISSUE TITLE
🙏 notification system add koren!   

### ISSUE THREAD

**Issue by Taraldinn** [techdiary-dev/Techdiary#54]
kew zokhon amar post comment othba like kore ami to janbo nah notoficvation syestem hoile vhalo hoy

**Comment by kingRayhan** [comment]
এই ইস্যূটি ইতিমধ্যেই ওপেন আছে #39 এ। বেসিক সব গুলা ফিচার পারফেক্টলি ইউজার ফ্রেন্ডলি হয়ে গেলে আমরা কমপ্লেক্স ফিচার নিয়ে কাজ শুরু করব।
