### ISSUE TITLE
🐞 ইডিটর এ crt + v এর মাধ্যমে ছবি আপলোড করা যাচ্ছে না। 

### ISSUE THREAD

**Issue by kingRayhan** [techdiary-dev/Techdiary#57]
ইডিটরে একসাথে একাদিক ছবি পেস্ট করলে এই সমস্যা করছে, একটি ছবি পেস্ট করলে আবার ঠিক মত কাজ করে।

![image](https://user-images.githubusercontent.com/7611746/116168239-c96d2780-a723-11eb-8c8b-cb40bf4ad0fb.png)

**Comment by shoaibsharif** [comment]
Did you find the cause yet?

**Comment by shoaibsharif** [comment]
This should resolve with latest commit. Resolving
