### ISSUE TITLE
গিট দিয়ে লগইন করতে গেলে ৪০৪ ইরোর আসছে🐞 

### ISSUE THREAD

**Issue by bohemianrazib** [techdiary-dev/Techdiary#59]
গিট দিয়ে লগইন করতে গেলে ৪০৪ ইরোর আসছে🐞

স্বাভাবিক ভাবে লগইন হবে আশা করেছিলাম

![screenshot-v3-api techdiary dev-2021 04 27-11_01_35](https://user-images.githubusercontent.com/61241962/116187959-5924cd00-a748-11eb-83d5-eea35b36a6be.png)

**Desktop (please complete the following information):**
 - OS: [windows10]
 - Browser [chrome]
 - Version [latest]

**Comment by kingRayhan** [comment]
@bohemianrazib ভাই ইস্যু দেয়ার জন্যে অনেক অনেক ধন্যবাদ। 
দয়া করে এখন একটু চেক করে জানাবেন কাজ করে কিনা?
