### ISSUE TITLE
🔥 হিরো এরিয়া তে ইসু এবং ইউ আই নিয়ে কিছু মতামত

### ISSUE THREAD

**Issue by biswajit-saha** [techdiary-dev/Techdiary#60]
**ইসুঃ** ছোট উইন্ডো তে ছবি এবং লেখা একটি আর একটির উপর উঠে যাচ্ছে।

![Screenshot 2021-04-26 223850](https://user-images.githubusercontent.com/17477852/116206129-1d93fe00-a75c-11eb-9f0d-56714b82b84e.jpg)

**সাজেশন**
* সাধারন টেক্সট এর স্থানে কিচু ট্যাগ ব্যবহার করা যেতে পারে।
* **যুক্ত হোন** লিঙ্কটি একটি বাটন হলে আরও ভাল ভাবে বোঝা যাবে এবং অন্য টেক্সট এর থেকে একটু আলাদা প্রায়োরিটি পাবে।
*  হিরো এরিয়ার সম্পূর্ণ অংশটি সেন্টার অ্যালাইনমেন্ট করলে হয়ত আর একটু ভাল লাগবে।
* প্রধান হেডিং (বাংলার প্রোগ্রামিং নেটয়ার্ক) এর ফন্ট ওয়েট বোল্ড করা যেতে পারে।
* এই পয়েন্ট টি কন্টেন্ত এরিয়ার জন্য। ডান পাশের সাইড বার এবং মাঝের প্রধান কন্টেন্ট এর মধ্যে আর একটু স্পেস বাড়াতে পারলে ভাল হয়। এখন প্রায় গায়ে গায়ে থাকায় কিছুটা ঘিঞ্জি লাগছে।

![Screenshot 2021-04-26 223707](https://user-images.githubusercontent.com/17477852/116207936-035b1f80-a75e-11eb-8066-0afc655837e8.jpg)

**Comment by shoaibsharif** [comment]
ধন্যবাদ আপনার গুরুত্বপুর্ণ মতামত ও সময়ের জন্যে। সরি আমি আসলে ইস্যু টা দেখেই সাথে সাথে ফিক্স করে ফেলেছিলাম। 
![CleanShot 2021-05-06 at 16 45 28](https://user-images.githubusercontent.com/29075110/117378736-dcea6200-ae8a-11eb-9aa8-86fc946ba01b.png)
আপনি ঠিকই বলেছেন আমাদের css এ কিছু সমস্যা ছিল, কিন্তু আমি মনে করি এখন মোবাইল এবং ডেস্কটপে ঠিক মত কাজ করছে। 
![CleanShot 2021-05-06 at 16 45 20](https://user-images.githubusercontent.com/29075110/117378816-06a38900-ae8b-11eb-9ed2-342cce50e371.png)

অবশ্যই আপনার আরো কিছু বলার থাকে, আমাদের জানাবেন
