### ISSUE TITLE
🐞  ডার্ক মোডে কোনো লিংক এবং কোড ব্লক গুলো দেখা যাচ্ছে না

### ISSUE THREAD

**Issue by asifadib** [techdiary-dev/Techdiary#65]
ডার্ক মোডে কোনো লিংক এবং কোড ব্লক গুলো দেখা যাচ্ছে না নিচে কিছু ছবি যুক্ত করেছি দেখলে বুঝতে পারবেন।

![image](https://user-images.githubusercontent.com/45002778/116393394-62469480-a843-11eb-9702-bbc1df1cfc75.png)

![image](https://user-images.githubusercontent.com/45002778/116393480-7f7b6300-a843-11eb-92e1-aa14eba76c6c.png)

![image](https://user-images.githubusercontent.com/45002778/116393529-8e621580-a843-11eb-99d2-1f85f1c3b3fe.png)

![image](https://user-images.githubusercontent.com/45002778/116393649-be111d80-a843-11eb-97d0-f81c4f9eb668.png)

মোবাইল এবং ডেক্সটপ কম্পিউটারে একই সমস্যা

**Comment by kingRayhan** [comment]
Problem fixed
