### ISSUE TITLE
💄 ইডিটরের আগের কোড ব্লকটাই ভালো ছিলো

### ISSUE THREAD

**Issue by asifadib** [techdiary-dev/Techdiary#67]
ইডিটরের আগের কোড ব্লকটাই ভালো ছিলো বর্তমানের কোড ব্লকটা ইউজারের ব্লগ পড়তে চোখে কিছুটা সমস্যা হয়। 

![image](https://user-images.githubusercontent.com/45002778/116395094-7d1a0880-a845-11eb-8d65-6ceab0ab220b.png)

![image](https://user-images.githubusercontent.com/45002778/116395229-acc91080-a845-11eb-8d8d-e2d526f7727d.png)

**Comment by shoaibsharif** [comment]
আমিও বিশ্বাস করি আগের এডিটর টা অনেক ভালো ছিল, কিন্তু সবাই মার্কডাউনটা আসলে বুঝে না। বুঝতে পারছি না কি করা যায়। @kingRayhan

**Comment by asifadib** [comment]
> আমিও বিশ্বাস করি আগের এডিটর টা অনেক ভালো ছিল, কিন্তু সবাই মার্কডাউনটা আসলে বুঝে না। বুঝতে পারছি না কি করা যায়। @kingRayhan

এখনকার ইডিটরটা ব্লগ লেখার জন্য খুবই উপযোগী এবং সহজ দ্রুত ব্লগ লিখা যায়। আমি বোঝাতে চেয়েছি কোড ব্লক গুলোর বর্তমান কালারটা তেমন সুন্দর ভাবে ফুটে ওঠে নাহ, আগের হাইলাইট কালারটাই অনেক ভালো ছিলো।

**Comment by kingRayhan** [comment]
@asifadib @shoaibsharif 

এবার দেখেন কেমন লাগে, ঠিক করে দিয়েছি।

### লাইট মোড
![image](https://user-images.githubusercontent.com/7611746/116692200-d157f080-a9dd-11eb-8097-cf9a7ad614df.png)


### ডার্ক মোড
![image](https://user-images.githubusercontent.com/7611746/116692269-e7fe4780-a9dd-11eb-914c-bb750ceaee56.png)

**Comment by shoaibsharif** [comment]
Nice.

**Comment by asifadib** [comment]
> @asifadib @shoaibsharif 
> 
> এবার দেখেন কেমন লাগে, ঠিক করে দিয়েছি।
> 
> ### লাইট মোড
> ![image](https://user-images.githubusercontent.com/7611746/116692200-d157f080-a9dd-11eb-8097-cf9a7ad614df.png)
> 
> 
> ### ডার্ক মোড
> ![image](https://user-images.githubusercontent.com/7611746/116692269-e7fe4780-a9dd-11eb-914c-bb750ceaee56.png)
> 

ভাইয়া যেমনটা প্রত্যাশা করেছি ঠিক তেমনই হয়েছে। আর এইটা সকল ব্যবহারকারীর জন্যই খুব ভালো হবে ব্লগ পড়তে ও সহজে বুঝতে পারবে কোনটা কোড ব্লক।

**Comment by asifadib** [comment]
ভাইয়া যেমনটা প্রত্যাশা 💖 করেছি ঠিক তেমনই হয়েছে। আর এইটা সকল ব্যবহারকারীর জন্যই খুব ভালো হবে ব্লগ পড়তে ও সহজে বুঝতে পারবে কোনটা কোড ব্লক।

**Comment by shoaibsharif** [comment]
Cool. Closing issue. If you see any other issue, please don't hesitate to create an issue.
