### ISSUE TITLE
💄Need to update skeleton for dark mode

### ISSUE THREAD

**Issue by anwarulislam** [techdiary-dev/Techdiary#68]
![image](https://user-images.githubusercontent.com/26295990/116566859-e9216d00-a928-11eb-88c3-a7f6476eba28.png)

**Comment by kingRayhan** [comment]
Solved

![image](https://user-images.githubusercontent.com/7611746/117557713-cc5b0700-b097-11eb-89b8-b24e8a9d388c.png)
