### ISSUE TITLE
🙏  Emoji

### ISSUE THREAD

**Issue by tanzilamd** [techdiary-dev/Techdiary#73]
post এর comment এ emoji এর option থাকলে ভালো হয় ।

**Comment by kingRayhan** [comment]
কমেন্ট বক্সে অনেক কাজ বাকি, আপাতত কোন রকম কমেন্ট দেখানো হচ্ছে। আপনার পরামর্শের জন্যে ধন্যবাদ।

**Comment by shoaibsharif** [comment]
ইমোজি এখন সব ধরনের কম্পিউটারেই আছে এটা কি আনার প্রয়োজন আছে?

**Comment by tanzilamd** [comment]
> ইমোজি এখন সব ধরনের কম্পিউটারেই আছে এটা কি আনার প্রয়োজন আছে?

just suggestion . (তবে আমার কম্পিউটার এ তো নাই।)
