### ISSUE TITLE
💄Logo Issue

### ISSUE THREAD

**Issue by thesharifdev** [techdiary-dev/Techdiary#76]
When I want to click the logo I feel it's too small. I think it should little bigger than now. (It's not major issue)

**Comment by kingRayhan** [comment]
Desktop স্ক্রিনে টেকডায়েরির ফুল টেক্স লোগোটি সো করানো উচিত আমার মনে হয় @shoaibsharif

**Comment by kingRayhan** [comment]
@sharif-go ভাই আমার মনে হয় এখন ঠিক আছে। আপনার কী মনে হয়?

![image](https://user-images.githubusercontent.com/7611746/117377867-0db3b100-aef6-11eb-880f-30b342b123a7.png)
