### ISSUE TITLE
🐞 Loading issue

### ISSUE THREAD

**Issue by thesharifdev** [techdiary-dev/Techdiary#77]
**আপনি যে সমস্যা(Bug) পেয়েছেন সেটি সংক্ষেপে ব্যক্ত করুন**
যখন আমি অন্য কারো প্রোফাইলে গিয়ে..ডাইরিতে ক্লিক করি তখন এটা কিছু সময়ের জন্য ফ্রিজ মনে হয়(ঘটনাটা আসলে লোডিং ইউআই না দেওয়া)।

**আপনি যেমনটি আশা করেছিলেন (Expected behavior)**
এখানে লোডিং হচ্ছে এমনটা হলে..user experience আরেকটু ভালো হবে বলে আমার মনে হয়।

যদিও এটাকে বাগ বলা যাবেনা...তবে এখানে লিখে ফেলছি তাই চেন্জ করলাম না

**Comment by kingRayhan** [comment]
@shoaibsharif

**Comment by shoaibsharif** [comment]
হুম এটা একটু প্রবলেম ছিল, ধন্যবাদ ধরিয়ে দেয়ার জন্যে। এখন নতুন কমিটে এই প্রবলেম সলভ করা হয়েছে
