### ISSUE TITLE
🐞 প্রোফাইল হালনাগাদ করা যাচ্ছে নাহ ! 

### ISSUE THREAD

**Issue by Taraldinn** [techdiary-dev/Techdiary#80]
**আপনি যে সমস্যা(Bug) পেয়েছেন সেটি সংক্ষেপে ব্যক্ত করুন**
// TODO: .. bug এর description এখানে লিখব

**আপনি যেমনটি আশা করেছিলেন (Expected behavior)**

**কিছু স্ক্রিনশট**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by kingRayhan** [comment]
কী সমস্যা করে একটা স্ক্রিনশট যুক্ত করতে বুঝতে সুবিদা হত।

**Comment by Taraldinn** [comment]
> কী সমস্যা করে একটা স্ক্রিনশট যুক্ত করতে বুঝতে সুবিদা হত।

![image](https://user-images.githubusercontent.com/59772487/117418608-6f4b3e00-af3d-11eb-87da-70cbb4c0bb3f.png)
![image](https://user-images.githubusercontent.com/59772487/117418661-7d995a00-af3d-11eb-99f9-18350a775f79.png)
![image](https://user-images.githubusercontent.com/59772487/117418735-93a71a80-af3d-11eb-8596-44567822a742.png)
![image](https://user-images.githubusercontent.com/59772487/117418772-9f92dc80-af3d-11eb-9f57-092f41066e96.png)

**Comment by nahid-emdad** [comment]
প্রোফাইল উপলোড করলে এমন হয়ে যাই । 😓
![image](https://user-images.githubusercontent.com/83067265/118964137-ff02da80-b988-11eb-97bc-864cfe5495a1.png)

**Comment by kingRayhan** [comment]
@nahid-emdad ভাই আপনাকে খুবই ধন্যবাদ ইস্যুটি জানানোর জন্যে।

**Comment by shoaibsharif** [comment]
It should work with my new commit

**Comment by kingRayhan** [comment]
@nahid-emdad ভাই দয়া করে দেখে একটু জানাবেন আপনার কাজ করছে কিনা এখন?

**Comment by nahid-emdad** [comment]
@kingRayhan  অসংখ্য ধন্যবাদ  আপনাকে। জি এখন কাজ করেছে । ❤😊

**Comment by kingRayhan** [comment]
@nahid-emdad পবর্তিতে কোন ইস্যু পেলে জানাজে ভুলবেন না দয়া করে।
