### ISSUE TITLE
🐞  ব্লগ পোস্টের ইউ আর এল সম্পূর্ণ বাংলায় সঠিক ভাবে দেখায় নাহ আগের মতো

### ISSUE THREAD

**Issue by asifadib** [techdiary-dev/Techdiary#81]
![image](https://user-images.githubusercontent.com/45002778/116931674-1ea8bc00-ac83-11eb-810a-f6eacd52bdbd.png)

**Comment by kingRayhan** [comment]
@shoaibsharif

**Comment by shoaibsharif** [comment]
URL আসলে আমরা কিছুই করছি না। যখন আপনি টাইটেল লিখছেন আমাদের ব্যাকেন্ড অভ্র এর লিখা গুলা ইংলিশে কনভার্ট করছে, আর আমাদের ইউনিক করার জন্যে লাস্টে কিছু অক্ষর Add করে দিয়েছি।

**Comment by asifadib** [comment]
![image](https://user-images.githubusercontent.com/45002778/117286420-00ada800-ae8b-11eb-884e-ad58f7b3a31f.png)


আমি আসলে কি বুঝাতে চেয়েছি উপরের স্ক্রিনশটটি লক্ষ্যে করলে বুঝতে পারবনে। এই ভাবে দিলে সার্চের জন্য অনেক ভালো হবে। তারপরও আপনারা ভালো বুঝেন।
