### ISSUE TITLE
💄 editor quote টা ঠিক করতে হবে 

### ISSUE THREAD

**Issue by Taraldinn** [techdiary-dev/Techdiary#83]
![image](https://user-images.githubusercontent.com/59772487/117224463-cf54be00-ae31-11eb-89a8-65a666913925.png)
এইখানে কুয়াটটা কোন ভাবেই মানাচ্ছে নাহ তা উপর বাংলা লেখায় ইটালিক একপ্রকার বাঙ্গি ! 
এডিটর টা যদি এমন কিছু হত ! 
![image](https://user-images.githubusercontent.com/59772487/117224530-f8754e80-ae31-11eb-9966-46327ad357ea.png)
![image](https://user-images.githubusercontent.com/59772487/117224554-09be5b00-ae32-11eb-9f3e-0a056acb7768.png)
তাহলে ভাল হত!

**Comment by kingRayhan** [comment]
@programmer-Quazi 

> একপ্রকার বাঙ্গি ! :smile: 

seriously :rofl:

**Comment by kingRayhan** [comment]
@programmer-Quazi ভাই এখন কেমন লাগে?

![image](https://user-images.githubusercontent.com/7611746/117371898-7dbc3a00-aeea-11eb-8fb2-f5db62b786b9.png)

**Comment by Taraldinn** [comment]
@kingRayhan এটা ঠিক আছে বাংলাটা ঠিক করেন ইটালিক টা !
