### ISSUE TITLE
🔥search 

### ISSUE THREAD

**Issue by tanzilamd** [techdiary-dev/Techdiary#88]
search bar এ search দিলে শুধু post অনুযায়ী result পাওয়া যায় । যদি search দিলে **post + user** এর নাম পাওয়া যেতো তাহলে ভালো হতো । 

### Search Bar
- user 
- post (আগে থেকেই আছে) 
- tag

**Comment by kingRayhan** [comment]
এটি একটি ভালো সাজেশন দিয়েছেন। ঠিক আছে, একটু ফ্রি হয়ে এটি নিয়ে কাজ করব আমরা।

**Comment by tanzilamd** [comment]
ওকে ভাইয়া
