### ISSUE TITLE
🙏  email verification 

### ISSUE THREAD

**Issue by tanzilamd** [techdiary-dev/Techdiary#90]
## Email confirmation / verification
**email verification system** add করলে আরও বেশি secure হবে বলে মনে করছি ।

**Comment by shoaibsharif** [comment]
যেহেতু আমরা নিজস্ব কোন ইমেল/পাসওয়ার্ড দিয়ে লগইন সিস্টেম আনি নাই, তাই এই ফিচার টা আনা হয় নি। যেহেতু আমরা ইউজারকে ইমেইল পরিবর্তন করার সুযোগ দিচ্ছি, আমরা খুবই শীঘ্রই আনব।
