### ISSUE TITLE
🙏 টেকডায়েড়িতে গ্রুপ ফিচার চাই।   

### ISSUE THREAD

**Issue by tanzilamd** [techdiary-dev/Techdiary#92]
group feature থাকলে হয়ত ভালো হয় ।
user রা নিজেদের ইচ্ছামত group খুলবে । 
- group

**Comment by kingRayhan** [comment]
মিডিয়ামের মত, অর্গানাইজেশন ফিচার আনার প্লান আছে আমাদের। যা অনেকটা গ্রুপের মতই হবে।
