### ISSUE TITLE
🐞  এল্গোলিয়া থেকে ডামি ডাটা গুলো সার্চ দিলে চলে আসতেছে!

### ISSUE THREAD

**Issue by itsrafsanjani** [techdiary-dev/Techdiary#93]
ডেভেলপমেন্ট এর জন ভিন্ন কালেকশন ব্যবহার করা উচিত।
![image](https://user-images.githubusercontent.com/48161278/118393798-b84c7200-b662-11eb-96ed-50f149c8a008.png)

**Comment by shoaibsharif** [comment]
Sorry for the late response and thank you for pointing that out. We have noticed that and changed Algolia API, but it seems some of them are still remains. We are fixing it as possible.

**Comment by shoaibsharif** [comment]
Issue should be fixed by now.
